import { Product } from "./types";

export const NOVA_PRODUCTS: Product[] = [
  // --- WOMEN ---
  {
    id: "w-1",
    name: "Aurelia Pleated Silk Evening Gown",
    subtitle: "Atelier Haute Couture",
    category: "Women",
    price: 349,
    originalPrice: 420,
    rating: 4.9,
    reviewsCount: 48,
    images: [
      "https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "Champagne Gold", hex: "#D4AF37" },
      { name: "Midnight Obsidian", hex: "#111111" },
      { name: "Burgundy Wine", hex: "#58111A" },
    ],
    description: "Flowing 100% mulberry silk silhouette with sunray micro-pleats, delicate halter neckline, and backless drape. Handcrafted in our Milan atelier.",
    details: [
      "100% Pure Mulberry Silk Georgette",
      "Concealed side zipper with delicate horn buttons",
      "Hand-rolled hems and French seams",
      "Floor-length sweeping train with weighted hem",
    ],
    fabricCare: [
      "Dry clean exclusively",
      "Steam iron on low setting",
      "Store in breathable garment bag",
    ],
    tag: "Haute Couture",
    inStock: true,
    isFeatured: true,
    isNewArrival: true,
  },
  {
    id: "w-2",
    name: "Milanese Double-Breasted Wool Trench",
    subtitle: "Heritage Outerwear",
    category: "Women",
    price: 489,
    originalPrice: 580,
    rating: 5.0,
    reviewsCount: 62,
    images: [
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Camel Beige", hex: "#C19A6B" },
      { name: "Onyx Black", hex: "#1C1C1C" },
      { name: "Sage Grey", hex: "#8A9A86" },
    ],
    description: "Structured double-faced Virgin wool trench coat featuring storm flaps, tortoiseshell belt buckle, and tailored peak lapels.",
    details: [
      "100% Italian Virgin Wool (520 GSM)",
      "Bemberg Cupro inner lining",
      "Removable sash belt with bespoke metallic clasp",
      "Deep welt hand pockets with fleece warmth lining",
    ],
    fabricCare: ["Specialist dry clean only", "Do not tumble dry"],
    tag: "Best Seller",
    inStock: true,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    id: "w-3",
    name: "Celeste Cashmere Ribbed Knit",
    subtitle: "Everyday Luxury",
    category: "Women",
    price: 219,
    originalPrice: 260,
    rating: 4.8,
    reviewsCount: 39,
    images: [
      "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "Ivory Cream", hex: "#FDFBF7" },
      { name: "Heather Grey", hex: "#9E9E9E" },
      { name: "Mocha", hex: "#7B5E57" },
    ],
    description: "Cloud-soft Mongolian cashmere mock-neck sweater with drop shoulders and elongated ribbed cuffs.",
    details: [
      "100% Grade-A Mongolian Cashmere",
      "Pill-resistant 2-ply yarn construction",
      "Seamless round-knit body",
      "Relaxed contemporary drape",
    ],
    fabricCare: ["Hand wash cold with wool shampoo", "Dry flat"],
    tag: "Essential",
    inStock: true,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    id: "w-4",
    name: "Valentina Sculpted Satin Midi Dress",
    subtitle: "Modern Elegance",
    category: "Women",
    price: 279,
    rating: 4.9,
    reviewsCount: 29,
    images: [
      "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "Emerald Green", hex: "#046307" },
      { name: "Noir", hex: "#121212" },
      { name: "Rose Quartz", hex: "#E0BFB8" },
    ],
    description: "Architectural cowl-back slip dress cut on the bias in lustrous heavy duchess satin.",
    details: [
      "Heavyweight 80g silk-poly satin blend",
      "Diagonal bias drape hugging contours effortlessly",
      "Adjustable spaghetti straps with gold-finish sliders",
      "Side slit for fluid movement",
    ],
    fabricCare: ["Dry clean recommended", "Cool steam iron inside-out"],
    tag: "Limited Drop",
    inStock: true,
    isFeatured: true,
    isNewArrival: false,
  },

  // --- MEN ---
  {
    id: "m-1",
    name: "Savile Bespoke Charcoal Wool Suit",
    subtitle: "Tailored Menswear",
    category: "Men",
    price: 699,
    originalPrice: 850,
    rating: 5.0,
    reviewsCount: 84,
    images: [
      "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["38R", "40R", "42R", "44R"],
    colors: [
      { name: "Charcoal Heather", hex: "#36454F" },
      { name: "Midnight Navy", hex: "#000080" },
      { name: "Pitch Black", hex: "#0F0F0F" },
    ],
    description: "Two-piece handcrafted suit cut from Super 130s merino wool with full floating canvas chest piece and horn buttons.",
    details: [
      "100% Super 130s Merino Wool woven in Biella, Italy",
      "Full canvas construction conforming naturally to posture",
      "Pick-stitched notch lapel and functional surgeon cuffs",
      "Trousers with side adjusters and unfinished hems for custom tailoring",
    ],
    fabricCare: ["Professional dry clean only", "Brush with horsehair brush after wear"],
    tag: "Bespoke",
    inStock: true,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    id: "m-2",
    name: "Como Raw Silk & Linen Overshirt",
    subtitle: "Resort Collection",
    category: "Men",
    price: 189,
    originalPrice: 220,
    rating: 4.7,
    reviewsCount: 31,
    images: [
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Ecru Linen", hex: "#F3EFE0" },
      { name: "Olive Earth", hex: "#556B2F" },
      { name: "Navy Ink", hex: "#1A2B4C" },
    ],
    description: "Breathable Italian raw linen overshirt with mother-of-pearl buttons and dual flap utility chest pockets.",
    details: [
      "65% Normandy Flax Linen, 35% Slub Raw Silk",
      "Garment washed for ultra-soft hand feel",
      "Camp collar design for versatile styling",
      "Natural horn button hardware",
    ],
    fabricCare: ["Machine wash gentle 30°C", "Hang dry in shade"],
    tag: "Summer Drop",
    inStock: true,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    id: "m-3",
    name: "Kyoto Heavy Selvedge Denim Jacket",
    subtitle: "Heritage Craft",
    category: "Men",
    price: 265,
    rating: 4.9,
    reviewsCount: 57,
    images: [
      "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Indigo Raw", hex: "#1F2937" },
      { name: "Washed Slate", hex: "#4B5563" },
    ],
    description: "14.5oz Japanese Kurabo shuttle-loom selvedge denim jacket with custom antique brass rivets and contrast copper stitching.",
    details: [
      "14.5oz 100% Cotton Japanese Selvedge",
      "Pink selvedge ID line along inner placket",
      "Reinforced bartacks at all stress points",
      "Custom embossed Nova Wear leather back patch",
    ],
    fabricCare: ["Cold soak inside-out", "Air dry naturally to create personal fades"],
    tag: "Japanese Denim",
    inStock: true,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    id: "m-4",
    name: "Verona Minimalist Merino Knit Polo",
    subtitle: "Smart Casual",
    category: "Men",
    price: 145,
    originalPrice: 175,
    rating: 4.8,
    reviewsCount: 43,
    images: [
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Forest Cypress", hex: "#1E3F20" },
      { name: "Black Caviar", hex: "#111111" },
      { name: "Sand Cream", hex: "#EAE0D0" },
    ],
    description: "Fine 18-gauge extra-fine merino wool knitted polo shirt with clean buttonless Johnny collar.",
    details: [
      "100% Extra-fine Australian Merino Wool (19.5 micron)",
      "Thermo-regulating and naturally odor resistant",
      "Knitted ribbed waistband that retains shape",
      "Pre-shrunk Italian spun yarn",
    ],
    fabricCare: ["Hand wash cold or wool cycle", "Dry flat away from direct heat"],
    tag: "Essential",
    inStock: true,
    isFeatured: false,
    isNewArrival: true,
  },

  // --- STREETWEAR ---
  {
    id: "st-1",
    name: "Cybernetics Oversized 500GSM Hoodie",
    subtitle: "Urban Subculture",
    category: "Streetwear",
    price: 165,
    originalPrice: 195,
    rating: 4.9,
    reviewsCount: 112,
    images: [
      "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Washed Carbon", hex: "#2B2D2F" },
      { name: "Concrete Grey", hex: "#8E9094" },
      { name: "Acid Lime", hex: "#C7EA46" },
    ],
    description: "Heavyweight 500 GSM loopback French terry fleece with boxy dropped shoulder cut, double-layered crossover hood, and discreet tonal rubberized branding.",
    details: [
      "500 GSM 100% Organic Combed Cotton",
      "Custom enzyme garment stone wash",
      "Seamless kangaroo front pocket",
      "Heavy 2x2 ribbing at hem and cuffs",
    ],
    fabricCare: ["Machine wash cold inside-out", "Do not iron print"],
    tag: "Trending",
    inStock: true,
    isFeatured: true,
    isNewArrival: true,
  },
  {
    id: "st-2",
    name: "Tactical Modular Cargo Trousers",
    subtitle: "Street Techwear",
    category: "Streetwear",
    price: 195,
    originalPrice: 240,
    rating: 4.8,
    reviewsCount: 76,
    images: [
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["30", "32", "34", "36"],
    colors: [
      { name: "Matte Black", hex: "#1A1A1A" },
      { name: "Military Khaki", hex: "#6B5B3E" },
    ],
    description: "Water-resistant ripstop cargo pants featuring 8 functional utility pockets, Fidlock magnetic buckle straps, and adjustable toggle ankles.",
    details: [
      "Cordura Ripstop with DWR water-repellent coating",
      "Articulated knee darts for unrestricted mobility",
      "German magnetic quick-release pocket closures",
      "Drawcord bungee cuff adjusters",
    ],
    fabricCare: ["Machine wash gentle", "Hang dry"],
    tag: "Techwear",
    inStock: true,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    id: "st-3",
    name: "Solaris Acid-Wash Boxy Graphic Tee",
    subtitle: "Limited Capsule",
    category: "Streetwear",
    price: 79,
    originalPrice: 95,
    rating: 4.7,
    reviewsCount: 65,
    images: [
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Vintage Mineral Wash", hex: "#3A3D40" },
      { name: "Bone White", hex: "#F5F2EB" },
    ],
    description: "Vintage 260 GSM single-jersey heavyweight tee with handcrafted distressed neckline and high-density screenprint graphic.",
    details: [
      "260 GSM 100% Pre-shrunk Ringspun Cotton",
      "Thick 1.25-inch ribbed crewneck collar",
      "Distressed micro-frays on cuffs and hem",
      "Pigment dyed for unique marbled wear",
    ],
    fabricCare: ["Cold wash", "Tumble dry low or air dry"],
    tag: "Capsule Drop",
    inStock: true,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    id: "st-4",
    name: "Apex Down-Filled Boxy Cropped Puffer",
    subtitle: "Winter Runway",
    category: "Streetwear",
    price: 320,
    originalPrice: 390,
    rating: 5.0,
    reviewsCount: 44,
    images: [
      "https://images.unsplash.com/photo-1544923246-77307dd654cb?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Metallic Chrome", hex: "#B8B8B8" },
      { name: "Pitch Black", hex: "#0A0A0A" },
      { name: "Cobalt Blue", hex: "#0047AB" },
    ],
    description: "700 fill-power goose down insulated outerwear jacket with matte water-repellent shell and oversized funnel collar.",
    details: [
      "Responsible Down Standard (RDS) 90/10 goose down",
      "Waterproof matte nylon ripstop fabric",
      "Internal fleece lined cuffs and storm flap",
      "Concealed interior security zip pocket",
    ],
    fabricCare: ["Specialist down dry cleaning only"],
    tag: "Winter Warmth",
    inStock: true,
    isFeatured: true,
    isNewArrival: false,
  },

  // --- ETHNIC WEAR ---
  {
    id: "et-1",
    name: "Royal Zardozi Embroidered Silk Sherwani",
    subtitle: "Heritage Royal Groom Collection",
    category: "Ethnic Wear",
    price: 780,
    originalPrice: 950,
    rating: 5.0,
    reviewsCount: 52,
    images: [
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["38", "40", "42", "44"],
    colors: [
      { name: "Ivory Cream & Gold", hex: "#FAF3E0" },
      { name: "Royal Midnight Blue", hex: "#0B132B" },
      { name: "Heritage Wine", hex: "#4A0E17" },
    ],
    description: "Magnificent raw silk sherwani intricately hand-embroidered with metallic gold zardozi thread, cutdana, and semi-precious beadwork. Includes matching silk churidar trousers and embroidered stole.",
    details: [
      "100% Pure Raw Varanasi Silk base",
      "Over 120 hours of master artisan hand embroidery",
      "Handcrafted metallic buttons with enamelled motifs",
      "Pure crepe lining for breathable ceremonial comfort",
    ],
    fabricCare: ["Strictly dry clean only", "Wrap in muslin cloth for preservation"],
    tag: "Royal Heritage",
    inStock: true,
    isFeatured: true,
    isNewArrival: true,
  },
  {
    id: "et-2",
    name: "Banarasi Handwoven Katan Silk Saree",
    subtitle: "Atelier Bridal Weaves",
    category: "Ethnic Wear",
    price: 450,
    originalPrice: 560,
    rating: 4.9,
    reviewsCount: 88,
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["Free Size (6.5m with blouse)"],
    colors: [
      { name: "Crimson Sindoor Red", hex: "#C41E3A" },
      { name: "Rani Hot Pink", hex: "#C71585" },
      { name: "Peacock Emerald", hex: "#097969" },
    ],
    description: "Authentic Katan silk heirloom saree woven with pure silver and gold zari in traditional floral jangla and regal paisley motifs on a pit loom.",
    details: [
      "100% Certified Mulberry Katan Silk with Silk Mark tag",
      "Real tested gold-plated silver zari thread work",
      "Grand heavy pallu with intricately woven temple borders",
      "Includes 1 meter unstitched designer blouse piece",
    ],
    fabricCare: ["Dry clean only", "Air every 6 months, avoid naphthalene balls"],
    tag: "Heirloom Weave",
    inStock: true,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    id: "et-3",
    name: "Noor Chanderi Silk Hand-Block Kurta Set",
    subtitle: "Celebration Wear",
    category: "Ethnic Wear",
    price: 230,
    originalPrice: 280,
    rating: 4.8,
    reviewsCount: 41,
    images: [
      "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Powder Blue", hex: "#B0E0E6" },
      { name: "Pastel Mint", hex: "#98FF98" },
      { name: "Blush Peach", hex: "#FFDAB9" },
    ],
    description: "Ethereal Chanderi silk three-piece ensemble adorned with delicate gota patti accents and hand-carved wooden block floral motifs. Paired with straight pants and organza dupatta.",
    details: [
      "Pure Chanderi Silk with soft cotton mulmul lining",
      "Hand-applied gota patti mirror-finish borders",
      "Airy featherlight organza dupatta with scalloped borders",
      "Comfortable elasticated waistband pants with side pocket",
    ],
    fabricCare: ["Dry clean recommended", "Iron on reverse with low heat"],
    tag: "Handmade",
    inStock: true,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    id: "et-4",
    name: "Mirza Pure Chikankari Men's Kurta & Bundi",
    subtitle: "Lucknow Artisanal Atelier",
    category: "Ethnic Wear",
    price: 299,
    originalPrice: 360,
    rating: 4.9,
    reviewsCount: 37,
    images: [
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000&auto=format&fit=crop",
    ],
    sizes: ["38", "40", "42", "44"],
    colors: [
      { name: "Pristine White", hex: "#FFFFFF" },
      { name: "Beige Almond", hex: "#EFDECD" },
      { name: "Sage Pastel", hex: "#BCB88A" },
    ],
    description: "Two-piece set featuring exquisite shadow-work Lucknowi Chikankari embroidery on pure hand-spun cotton silk, complemented by a tailored Nehru jacket with metallic buttons.",
    details: [
      "Pure Mulberry Cotton-Silk blend",
      "Intricate Bakhiya and Phanda needlework by master artisans",
      "Mandarin collar with concealed button placket",
      "Includes tailored Bundi waistcoat and cotton pajama",
    ],
    fabricCare: ["Gentle dry clean only"],
    tag: "Artisanal",
    inStock: true,
    isFeatured: true,
    isNewArrival: true,
  },
];

export const LOOKBOOK_GALLERY = [
  {
    title: "The Autumn Runway '26",
    subtitle: "Milan Fashion Week Capsule",
    img: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop",
    category: "Runway",
  },
  {
    title: "Urban Architecture",
    subtitle: "Tokyo Streetwear Editorial",
    img: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop",
    category: "Streetwear",
  },
  {
    title: "Modern Silk & Saree",
    subtitle: "Royal Heritage Exhibition",
    img: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop",
    category: "Ethnic",
  },
  {
    title: "Bespoke Sartorialist",
    subtitle: "Handmade English Woolens",
    img: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=1000&auto=format&fit=crop",
    category: "Menswear",
  },
  {
    title: "Evening Radiance",
    subtitle: "Monaco Gala Couture",
    img: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop",
    category: "Haute Couture",
  },
  {
    title: "Minimalist Warmth",
    subtitle: "Grade-A Mongolian Cashmere",
    img: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=1000&auto=format&fit=crop",
    category: "Essentials",
  },
];

export const BRAND_VALUES = [
  {
    title: "Atelier Craftsmanship",
    desc: "Every cut, seam, and embroidery is drafted by senior pattern makers with over two decades of European & Asian haute couture heritage.",
    icon: "Crown",
  },
  {
    title: "100% Ethical & Sustainable",
    desc: "We exclusively source certified Mulberry silks, organic cottons, and mulesing-free wools with zero synthetic microplastic runoffs.",
    icon: "Leaf",
  },
  {
    title: "Bespoke Fitting Concierge",
    desc: "Order standard sizes or schedule a complimentary virtual or showroom fitting with our private master tailors.",
    icon: "Scissors",
  },
  {
    title: "Complimentary Global Express",
    desc: "Dispatched in signature luxury matte black boxes with climate-neutral carbon compensated courier delivery.",
    icon: "PackageCheck",
  },
];
