import { ElectronicsProduct, ElectronicsCategory } from "./types";

export const CATEGORIES_DATA: {
  id: ElectronicsCategory;
  name: string;
  iconName: string;
  itemCount: number;
  image: string;
  description: string;
}[] = [
  {
    id: "Smartphones",
    name: "Smartphones",
    iconName: "Smartphone",
    itemCount: 24,
    image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?q=80&w=800&auto=format&fit=crop",
    description: "Flagship 5G cameras, folding screens & OLED power",
  },
  {
    id: "Laptops",
    name: "Laptops",
    iconName: "Laptop",
    itemCount: 18,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop",
    description: "High-performance ultrabooks, creator rigs & business machines",
  },
  {
    id: "Smart TVs",
    name: "Smart TVs",
    iconName: "Tv",
    itemCount: 12,
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=800&auto=format&fit=crop",
    description: "4K & 8K Quantum Mini-LED, OLED cinema screens",
  },
  {
    id: "Tablets",
    name: "Tablets",
    iconName: "Tablet",
    itemCount: 15,
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=800&auto=format&fit=crop",
    description: "Creativity canvases with ultra-responsive pen support",
  },
  {
    id: "Smartwatches",
    name: "Smartwatches",
    iconName: "Watch",
    itemCount: 20,
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=800&auto=format&fit=crop",
    description: "Titanium chassis, ECG heart health & sport GPS",
  },
  {
    id: "Headphones & Earbuds",
    name: "Audio & Headphones",
    iconName: "Headphones",
    itemCount: 26,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop",
    description: "Lossless spatial audio and active noise cancellation",
  },
  {
    id: "Gaming",
    name: "Gaming Gear",
    iconName: "Gamepad2",
    itemCount: 30,
    image: "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?q=80&w=800&auto=format&fit=crop",
    description: "Low-latency wireless peripherals and mechanical rigs",
  },
  {
    id: "Accessories",
    name: "Accessories",
    iconName: "Cpu",
    itemCount: 45,
    image: "https://images.unsplash.com/photo-1622445262464-84b1456045b6?q=80&w=800&auto=format&fit=crop",
    description: "GaN chargers, MagSafe docks, adapters & speakers",
  },
];

export const PRODUCTS_DATA: ElectronicsProduct[] = [
  {
    id: "tech-1",
    name: "NovaPhone 16 Pro Max 5G",
    brand: "TECHNOVA",
    category: "Smartphones",
    price: 1199,
    originalPrice: 1399,
    discountPercent: 14,
    rating: 4.9,
    reviewsCount: 384,
    badge: "BEST SELLER",
    image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?q=80&w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?q=80&w=800&auto=format&fit=crop",
    ],
    description:
      "Engineered with aerospace-grade brushed titanium, the NovaPhone 16 Pro Max delivers an unparalleled 6.9-inch 120Hz Super Retina OLED display, Octa-Core AI Neural Engine, and cinematic 5x optical periscope zoom camera with ProRes 4K60 video recording.",
    specs: [
      { name: "Display", value: "6.9\" OLED, 120Hz ProMotion, 2500 nits peak" },
      { name: "Processor", value: "Nova A18 Bionic 3nm Neural Processor" },
      { name: "Camera", value: "48MP Main + 48MP Ultra-wide + 12MP 5x Periscope" },
      { name: "Battery", value: "4,850 mAh with 30W Qi2 Fast Wireless" },
      { name: "Security", value: "Ultrasonic 3D In-Display & Facial Biometrics" },
      { name: "Durability", value: "IP68 Water/Dust Resistance & Ceramic Shield" },
    ],
    variants: [
      { name: "Natural Titanium - 256GB", colorName: "Natural Titanium", colorHex: "#9E9E9E", storageOrSize: "256GB", priceModifier: 0 },
      { name: "Midnight Black - 512GB", colorName: "Midnight Black", colorHex: "#1A1A1A", storageOrSize: "512GB", priceModifier: 150 },
      { name: "Desert Titanium - 1TB", colorName: "Desert Titanium", colorHex: "#C5A880", storageOrSize: "1TB", priceModifier: 350 },
    ],
    inStock: true,
    stockCount: 18,
    isFeatured: true,
    isDeal: true,
    reviews: [
      {
        id: "r1",
        author: "Marcus Vance",
        rating: 5,
        date: "2 days ago",
        title: "The best smartphone I have ever held",
        comment: "The titanium finish is exceptionally lightweight and the low-light camera capabilities exceed my dedicated mirrorless rig for quick travel shots.",
        verified: true,
      },
      {
        id: "r2",
        author: "Elena Rostova",
        rating: 5,
        date: "1 week ago",
        title: "Insane battery life & display quality",
        comment: "Full day of heavy usage with 40% battery remaining by bedtime. 120Hz display is butter smooth.",
        verified: true,
      },
    ],
  },
  {
    id: "tech-2",
    name: "NovaBook Studio 16\" M3 Ultra",
    brand: "TECHNOVA",
    category: "Laptops",
    price: 2399,
    originalPrice: 2699,
    discountPercent: 11,
    rating: 4.95,
    reviewsCount: 241,
    badge: "CREATOR RIG",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=800&auto=format&fit=crop",
    ],
    description:
      "A masterpiece for software engineers, 3D artists and video producers. Featuring the Nova M3 Ultra 16-Core CPU, 40-Core GPU, Liquid Retina XDR Mini-LED screen with 1600 nits peak HDR, and up to 22 hours of continuous battery efficiency.",
    specs: [
      { name: "Display", value: "16.2\" Liquid Retina XDR (3456 x 2234), 120Hz" },
      { name: "Processor", value: "16-Core M3 Ultra with 40-Core GPU" },
      { name: "Memory", value: "48GB Unified High-Bandwidth RAM" },
      { name: "Storage", value: "1TB PCIe Gen4 NVMe SSD (up to 7.4GB/s)" },
      { name: "Battery", value: "100Wh Lithium Polymer (Up to 22h battery)" },
      { name: "Ports", value: "3x Thunderbolt 4, HDMI 2.1, SDXC Slot, MagSafe" },
    ],
    variants: [
      { name: "Space Black - 48GB / 1TB", colorName: "Space Black", colorHex: "#1E1E24", storageOrSize: "48GB / 1TB", priceModifier: 0 },
      { name: "Silver Frost - 64GB / 2TB", colorName: "Silver Frost", colorHex: "#E2E8F0", storageOrSize: "64GB / 2TB", priceModifier: 400 },
    ],
    inStock: true,
    stockCount: 9,
    isFeatured: true,
    isNewArrival: true,
    reviews: [
      {
        id: "r3",
        author: "Devon Chen",
        rating: 5,
        date: "3 days ago",
        title: "Compiles our microservices instantly",
        comment: "Fan noise is virtually non-existent even under maximum compiling load. The display contrast is reference-monitor grade.",
        verified: true,
      },
    ],
  },
  {
    id: "tech-3",
    name: "NovaVision 65\" Quantum 4K Mini-LED",
    brand: "TECHNOVA",
    category: "Smart TVs",
    price: 1499,
    originalPrice: 1899,
    discountPercent: 21,
    rating: 4.85,
    reviewsCount: 168,
    badge: "TODAY'S DEAL -21%",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop",
    ],
    description:
      "Transform your living room into a private IMAX theater. Features 2,048 local dimming zones, Quantum Dot color vibrancy, Dolby Vision IQ, IMAX Enhanced, and 144Hz VRR gaming mode with 4x HDMI 2.1 inputs.",
    specs: [
      { name: "Resolution", value: "4K UHD (3840 x 2160) Quantum Mini-LED" },
      { name: "Refresh Rate", value: "144Hz Native Variable Refresh Rate (VRR)" },
      { name: "Brightness", value: "2,200 nits peak with 2,048 Dimming Zones" },
      { name: "Audio", value: "60W 4.2.2 Channel Dolby Atmos & DTS:X" },
      { name: "Smart OS", value: "NovaOS AI with Google TV & Apple AirPlay 2" },
    ],
    variants: [
      { name: "65-Inch Bezel-less", storageOrSize: "65\"", priceModifier: 0 },
      { name: "75-Inch Cinema Edition", storageOrSize: "75\"", priceModifier: 500 },
    ],
    inStock: true,
    stockCount: 12,
    isFeatured: true,
    isDeal: true,
    reviews: [
      {
        id: "r4",
        author: "Sarah K.",
        rating: 5,
        date: "2 weeks ago",
        title: "Deep blacks like OLED with stunning HDR brightness",
        comment: "No blooming around subtitles and PS5 gaming at 4K 120Hz is breathtaking. Setup was effortless.",
        verified: true,
      },
    ],
  },
  {
    id: "tech-4",
    name: "NovaWatch Ultra 2 Titanium GPS",
    brand: "TECHNOVA",
    category: "Smartwatches",
    price: 749,
    originalPrice: 899,
    discountPercent: 17,
    rating: 4.9,
    reviewsCount: 512,
    badge: "FLASH DEAL",
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800&auto=format&fit=crop",
    ],
    description:
      "Crafted for extreme endurance and everyday elegance. Aviation-grade 49mm titanium case, 3000-nit sapphire crystal display, dual-frequency precision GPS, underwater depth gauge up to 40m, and 72-hour battery endurance.",
    specs: [
      { name: "Case", value: "49mm Grade 5 Aerospace Titanium" },
      { name: "Display", value: "Sapphire Crystal OLED, 3000 nits Always-On" },
      { name: "Sensors", value: "ECG, SpO2 Blood Oxygen, Skin Temp, Depth Meter" },
      { name: "Water Rating", value: "100m Water Resistant, EN13319 Dive Certified" },
      { name: "Battery", value: "Up to 72 hours in Low Power Mode" },
    ],
    variants: [
      { name: "Titanium / Orange Trail Loop", colorName: "Orange Trail", colorHex: "#FF6B35", storageOrSize: "49mm", priceModifier: 0 },
      { name: "Titanium / Midnight Ocean Band", colorName: "Midnight Navy", colorHex: "#1E3A8A", storageOrSize: "49mm", priceModifier: 0 },
    ],
    inStock: true,
    stockCount: 25,
    isDeal: true,
    isFeatured: true,
    reviews: [
      {
        id: "r5",
        author: "Julian Thorne",
        rating: 5,
        date: "5 days ago",
        title: "Tough as nails and looks gorgeous with a suit",
        comment: "Used it on a 4-day alpine trek without needing a charger. The GPS precision mapped every switchback accurately.",
        verified: true,
      },
    ],
  },
  {
    id: "tech-5",
    name: "NovaPods Studio Spatial Audio Earbuds",
    brand: "TECHNOVA",
    category: "Headphones & Earbuds",
    price: 249,
    originalPrice: 299,
    discountPercent: 17,
    rating: 4.88,
    reviewsCount: 720,
    badge: "TOP RATED",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?q=80&w=800&auto=format&fit=crop",
    ],
    description:
      "Next-generation acoustic architecture delivering adaptive active noise cancellation, personalized 3D spatial audio with dynamic head tracking, transparency mode, and crystal clear multi-beam microphones.",
    specs: [
      { name: "Acoustics", value: "Custom high-excursion driver & low-distortion amp" },
      { name: "Noise Control", value: "Hybrid Active Noise Cancellation 2.0 (-45dB)" },
      { name: "Battery Life", value: "8h per charge, 36h total with MagSafe USB-C Case" },
      { name: "Connectivity", value: "Bluetooth 5.4 with LDAC & Multipoint Pairing" },
      { name: "Protection", value: "IP54 Sweat and Dust Resistant" },
    ],
    variants: [
      { name: "Ceramic White", colorName: "Ceramic White", colorHex: "#F8FAFC", priceModifier: 0 },
      { name: "Cyber Matte Black", colorName: "Matte Black", colorHex: "#0F172A", priceModifier: 0 },
    ],
    inStock: true,
    stockCount: 40,
    isFeatured: true,
    isDeal: true,
    reviews: [
      {
        id: "r6",
        author: "Amara Patel",
        rating: 5,
        date: "Yesterday",
        title: "Noise cancellation deletes subway noise completely",
        comment: "Audio stage is wide, punchy bass without overpowering mids. Ear fit is secure during sprints.",
        verified: true,
      },
    ],
  },
  {
    id: "tech-6",
    name: "NovaSound Max Wireless Over-Ear",
    brand: "TECHNOVA",
    category: "Headphones & Earbuds",
    price: 399,
    originalPrice: 479,
    discountPercent: 16,
    rating: 4.92,
    reviewsCount: 310,
    badge: "AUDIOPHILE",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=800&auto=format&fit=crop",
    ],
    description:
      "Crafted with anodized aluminum earcups, breathable knit-mesh canopy headband, and 40mm titanium drivers for studio-master acoustic precision and ultra-quiet isolation.",
    specs: [
      { name: "Drivers", value: "40mm custom titanium dual-magnet diaphragm" },
      { name: "Frequency Response", value: "4Hz – 42,000Hz Hi-Res Lossless" },
      { name: "Battery", value: "40 hours continuous playback with fast 10-min boost" },
      { name: "Material", value: "Anodized aluminum & memory foam lambskin cups" },
    ],
    variants: [
      { name: "Graphite Silver", colorName: "Graphite Silver", colorHex: "#4B5563", priceModifier: 0 },
      { name: "Sky Azure Blue", colorName: "Sky Azure", colorHex: "#0284C7", priceModifier: 0 },
    ],
    inStock: true,
    stockCount: 15,
    isNewArrival: true,
    reviews: [
      {
        id: "r7",
        author: "Leon S.",
        rating: 5,
        date: "4 days ago",
        title: "Pure acoustic bliss",
        comment: "The soundstage is breathtaking. Comfortable enough to wear through an 8-hour workday.",
        verified: true,
      },
    ],
  },
  {
    id: "tech-7",
    name: "NovaPad Pro 12.9\" OLED with Stylus",
    brand: "TECHNOVA",
    category: "Tablets",
    price: 999,
    originalPrice: 1199,
    discountPercent: 17,
    rating: 4.87,
    reviewsCount: 195,
    badge: "CREATOR CHOICE",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1561154464-82e9adf32764?q=80&w=800&auto=format&fit=crop",
    ],
    description:
      "A dual-layer OLED ultra-thin tablet delivering 1000 nits full-screen brightness, M3 efficiency, low-latency magnetic wireless stylus charging, and quad-speaker spatial sound.",
    specs: [
      { name: "Screen", value: "12.9\" Ultra Retina Tandem OLED, 120Hz" },
      { name: "Thickness", value: "5.1mm ultra-slim aerodynamic aluminum shell" },
      { name: "Chip", value: "Nova M3 with 10-core GPU & Hardware Ray Tracing" },
      { name: "Stylus", value: "Includes Nova Pen Pro with haptic feedback & tilt" },
    ],
    variants: [
      { name: "Space Gray - 256GB WiFi", colorName: "Space Gray", colorHex: "#374151", storageOrSize: "256GB", priceModifier: 0 },
      { name: "Space Gray - 512GB 5G Cellular", colorName: "Space Gray", colorHex: "#374151", storageOrSize: "512GB 5G", priceModifier: 200 },
    ],
    inStock: true,
    stockCount: 14,
    isFeatured: true,
    isDeal: true,
    reviews: [
      {
        id: "r8",
        author: "Clara Wong",
        rating: 5,
        date: "6 days ago",
        title: "Replaced my laptop for illustration & meetings",
        comment: "Zero lag when sketching in Procreate. The tandem OLED screen is unmatched.",
        verified: true,
      },
    ],
  },
  {
    id: "tech-8",
    name: "NovaStrike Apex Optical Gaming Keyboard",
    brand: "TECHNOVA",
    category: "Gaming",
    price: 189,
    originalPrice: 229,
    discountPercent: 17,
    rating: 4.89,
    reviewsCount: 420,
    badge: "ESPORTS GEAR",
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800&auto=format&fit=crop",
    ],
    description:
      "Rapid-trigger Hall Effect magnetic switches with 0.1mm adjustable actuation, per-key RGB lighting, solid CNC aircraft aluminum body, and magnetic memory-foam wrist rest.",
    specs: [
      { name: "Switches", value: "Hall-Effect Magnetic Analog Switches (0.1–4.0mm)" },
      { name: "Polling Rate", value: "8,000Hz Hyper-Polling (0.125ms latency)" },
      { name: "Chassis", value: "Aircraft Grade 5052 CNC Aluminum Top Plate" },
      { name: "Connectivity", value: "Detachable Braided Type-C & 2.4GHz UltraSync" },
    ],
    variants: [
      { name: "Stealth Black Edition", colorName: "Stealth Black", colorHex: "#111827", priceModifier: 0 },
      { name: "Cyber White Edition", colorName: "Cyber White", colorHex: "#F3F4F6", priceModifier: 10 },
    ],
    inStock: true,
    stockCount: 30,
    isNewArrival: true,
    reviews: [
      {
        id: "r9",
        author: "Tyler 'Apex' G.",
        rating: 5,
        date: "3 days ago",
        title: "Immediate competitive advantage in CS2 and Valorant",
        comment: "Rapid trigger feels like cheating. The build quality is rock solid and heavy.",
        verified: true,
      },
    ],
  },
  {
    id: "tech-9",
    name: "NovaBoom 360 Waterproof Smart Speaker",
    brand: "TECHNOVA",
    category: "Accessories",
    price: 159,
    originalPrice: 199,
    discountPercent: 20,
    rating: 4.82,
    reviewsCount: 280,
    badge: "TODAY'S DEAL -20%",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=800&auto=format&fit=crop",
    ],
    description:
      "Room-filling 360-degree immersive acoustic sound with dual passive radiators, IP67 waterproof & floatable design, ambient RGB beat sync, and 24-hour battery with built-in powerbank.",
    specs: [
      { name: "Output", value: "60W RMS 360° Omnidirectional Stereo" },
      { name: "Waterproof", value: "IP67 Submersible & Dustproof" },
      { name: "Battery", value: "7,500 mAh battery (24h playback + phone charging)" },
      { name: "Pairing", value: "PartyLink connects up to 100 NovaBoom units" },
    ],
    variants: [
      { name: "Obsidian Black", colorName: "Obsidian Black", colorHex: "#18181B", priceModifier: 0 },
      { name: "Electric Cyan", colorName: "Electric Cyan", colorHex: "#06B6D4", priceModifier: 0 },
      { name: "Sunset Orange", colorName: "Sunset Orange", colorHex: "#F97316", priceModifier: 0 },
    ],
    inStock: true,
    stockCount: 35,
    isDeal: true,
    reviews: [
      {
        id: "r10",
        author: "Nina Morales",
        rating: 5,
        date: "1 week ago",
        title: "Huge sound in a rugged portable design",
        comment: "Took it kayaking and it took splashes easily. Bass rattles the patio table.",
        verified: true,
      },
    ],
  },
  {
    id: "tech-10",
    name: "NovaPower 140W GaN 4-Port Fast Charger",
    brand: "TECHNOVA",
    category: "Accessories",
    price: 79,
    originalPrice: 99,
    discountPercent: 20,
    rating: 4.94,
    reviewsCount: 650,
    badge: "TRAVEL ESSENTIAL",
    image: "https://images.unsplash.com/photo-1622445262464-84b1456045b6?q=80&w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1622445262464-84b1456045b6?q=80&w=800&auto=format&fit=crop",
    ],
    description:
      "Gallium Nitride (GaN III) high-efficiency travel charger capable of delivering 140W single-port PD 3.1 speed to charge a 16\" laptop to 50% in just 28 minutes, while powering three other devices simultaneously.",
    specs: [
      { name: "Total Power", value: "140W GaN III Fast Charge" },
      { name: "Ports", value: "3x USB-C PD 3.1 + 1x USB-A QC 4.0" },
      { name: "Safety", value: "ActiveProtect temp monitoring 3 million times/day" },
      { name: "Form Factor", value: "40% smaller than standard 140W bricks" },
    ],
    variants: [
      { name: "Dark Titanium Gray", colorName: "Dark Titanium", colorHex: "#374151", priceModifier: 0 },
      { name: "Arctic White", colorName: "Arctic White", colorHex: "#FFFFFF", priceModifier: 0 },
    ],
    inStock: true,
    stockCount: 50,
    isFeatured: true,
    reviews: [
      {
        id: "r11",
        author: "David L.",
        rating: 5,
        date: "2 days ago",
        title: "Replaced 4 different chargers in my travel bag",
        comment: "Charges my MacBook Pro 16, iPhone, and Apple Watch at full speed at once without getting hot.",
        verified: true,
      },
    ],
  },
];
